import { Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowUpRight, Check, Dumbbell, Salad, Target, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getTemplate, gym, food } from "@/lib/website";
import { usePacks } from "@/lib/crm";
import { MENU_CATS, useMenu } from "@/lib/kitchen";
export function WebsiteHome({ id }: { id: string }) {
  const t = getTemplate(id); if (!t) return null;
  return <>
    <section className="web-hero relative flex items-center overflow-hidden">
      <img src={t.image} alt={id === "balance" ? "Nutrición fitness: bowl y batido" : "Instalaciones de entrenamiento de fuerza"} width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover" />
      <div className="absolute inset-0 bg-photo-shade/50" />
      <div className="relative mx-auto w-full max-w-7xl px-6 py-12 text-photo-foreground md:px-10"><p className="mb-5 text-xs font-semibold uppercase">Entrenamiento / Nutrición / Comunidad</p><h1 className="max-w-2xl text-5xl font-extrabold sm:text-7xl">{t.headline}</h1><p className="mt-5 max-w-md text-lg">{t.subtitle}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/web/$plantilla/planes" params={{ plantilla: id }}>Conoce los planes <ArrowUpRight /></Link></Button><Button asChild variant="outline" size="lg"><Link to="/web/$plantilla/contacto" params={{ plantilla: id }}>Agenda tu visita</Link></Button></div></div>
    </section>
    <section className="border-b px-6 py-9"><div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-3">{[{ icon: Dumbbell, title: "Entrena con propósito", text: "Fuerza, acondicionamiento y rutinas para tus objetivos." }, { icon: Target, title: "Enfócate en tu progreso", text: "Seguimiento corporal y acompañamiento personalizado." }, { icon: Salad, title: "Nutre tus resultados", text: "Batidos, bowls y comidas con macros a la vista." }].map(x => <div key={x.title} className="flex gap-4"><x.icon className="mt-1 size-6 shrink-0 text-primary" /><div><h2 className="text-sm font-bold">{x.title}</h2><p className="mt-2 text-sm text-muted-foreground">{x.text}</p></div></div>)}</div></section>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-16 md:grid-cols-2"><img src={id === "balance" ? gym : food} alt={id === "balance" ? "Zona de fuerza" : "Comida saludable y smoothie"} loading="lazy" width={1536} height={1024} className="aspect-[4/3] w-full rounded-lg object-cover" /><div><p className="text-xs uppercase text-primary">Más que un gimnasio</p><h2 className="mt-4 text-3xl font-bold">Tu entrenamiento no termina en la última repetición.</h2><p className="mt-5 text-muted-foreground">Haz de tu bienestar una rutina. Combina tu membresía con sesiones de entrenamiento y nuestra cocina fitness.</p><Button asChild className="mt-7"><Link to="/web/$plantilla/cocina" params={{ plantilla: id }}>Descubre la cocina <ArrowUpRight /></Link></Button></div></section>
  </>;
}
export function WebsitePlans({ id }: { id: string }) {
  const packs = usePacks().filter(p => p.active);
  return <section className="mx-auto max-w-7xl px-6 py-14"><p className="text-xs uppercase text-primary">Membresías & experiencias</p><h1 className="mt-3 text-4xl font-bold">Planes Gym Black</h1><p className="mt-4 text-muted-foreground">Elige cómo quieres entrenar.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{packs.map(p => <article key={p.id} className="flex flex-col rounded-lg border bg-card p-6"><h2 className="min-h-14 text-xl font-bold">{p.name}</h2><p className="mt-5 text-3xl font-bold">{p.price.toLocaleString("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 })}</p><p className="mt-2 text-sm text-muted-foreground">Vigencia de {p.days} días</p><ul className="my-6 flex-1 space-y-4 text-sm">{[p.accesses, ...(p.sessions ? [`${p.sessions} sesiones de entrenamiento`] : []), ...(p.cafe !== "—" ? [p.cafe] : []), p.extras].filter(Boolean).map(x => <li key={x} className="flex gap-2"><Check className="size-4 shrink-0 text-primary" />{x}</li>)}</ul><p className="mb-5 text-xs text-muted-foreground">Sucursales: {p.branches.join(", ")}</p><Button asChild className="w-full"><Link to="/web/$plantilla/contacto" params={{ plantilla: id }}>Me interesa <ArrowUpRight /></Link></Button></article>)}</div></section>;
}
export function WebsiteKitchen({ id }: { id: string }) {
  const [category, setCategory] = useState("Todos"); const menu = useMenu().filter(m => m.available && (category === "Todos" || m.cat === category));
  return <><section className="relative flex min-h-80 items-center px-6 py-14"><img src={food} width={1536} height={1024} alt="Bowls y protein bar" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-photo-shade/55" /><div className="relative mx-auto w-full max-w-7xl text-photo-foreground"><p className="text-xs uppercase">Smoothie & Protein Bar</p><h1 className="mt-4 text-4xl font-bold">Cocina fitness</h1><p className="mt-4 max-w-md">Sabor y nutrición para tu recuperación.</p></div></section><section className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-wrap gap-2" aria-label="Categorías de cocina">{["Todos", ...MENU_CATS].map(c => <Button key={c} variant={c === category ? "default" : "outline"} onClick={() => setCategory(c)}>{c}</Button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{menu.map(m => <article key={m.id} className="rounded-lg border bg-card p-5"><p className="text-xs text-primary">{m.cat}</p><h2 className="mt-2 text-lg font-bold">{m.name}</h2><div className="mt-4 flex justify-between gap-2"><span className="font-bold">${m.price} MXN</span><span className="text-sm text-muted-foreground">{m.kcal} kcal</span></div><p className="mt-4 border-t pt-3 text-xs text-muted-foreground">Proteína {m.p} g · Carbs {m.c} g · Grasas {m.f} g</p></article>)}</div><Button asChild className="mt-8"><Link to="/">Accede para pedir <ArrowUpRight /></Link></Button></section></>;
}
export function WebsiteContact() {
  const [sent, setSent] = useState(false);
  return <section className="mx-auto max-w-7xl px-6 py-14"><p className="text-xs uppercase text-primary">Da el primer paso</p><h1 className="mt-3 text-4xl font-bold">Visita Gym Black</h1><div className="mt-10 grid gap-12 md:grid-cols-2"><div><h2 className="text-2xl font-bold">Hablemos de tus objetivos.</h2><p className="mt-4 text-muted-foreground">Fuerza, condición física o bienestar: encuentra tu punto de partida.</p><div className="mt-8 space-y-4">{["Entrenamiento personalizado", "Membresías y paquetes", "Cocina y nutrición fitness"].map(x => <p key={x} className="flex gap-3 text-sm"><Check className="size-4 text-primary" />{x}</p>)}</div><div className="mt-10 border-t pt-6"><p className="flex items-center gap-2 text-sm font-semibold"><MapPin className="size-4 text-primary" /> Sucursales</p><p className="mt-3 text-sm text-muted-foreground">Ubicaciones y horarios por confirmar.</p></div></div><div>{sent ? <div role="status" className="border-t py-8"><Check className="size-10 text-primary" /><h2 className="mt-4 text-2xl font-bold">Solicitud de ejemplo completada</h2><p className="mt-3 text-muted-foreground">No se ha enviado ningún mensaje. Esta página está en modo demostración.</p><Button variant="outline" className="mt-6" onClick={() => setSent(false)}>Nueva solicitud</Button></div> : <form className="space-y-5" onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="space-y-2"><Label htmlFor="visit-name">Nombre</Label><Input id="visit-name" required autoComplete="name" placeholder="Tu nombre" /></div><div className="space-y-2"><Label htmlFor="visit-email">Correo electrónico</Label><Input id="visit-email" type="email" required autoComplete="email" placeholder="tu@correo.com" /></div><div className="space-y-2"><Label htmlFor="visit-phone">Teléfono</Label><Input id="visit-phone" type="tel" required autoComplete="tel" /></div><div className="space-y-2"><Label htmlFor="visit-goal">Tu objetivo</Label><Input id="visit-goal" required placeholder="¿Qué te gustaría lograr?" /></div><p className="text-xs text-muted-foreground">Formulario de demostración. No envía ni guarda tus datos.</p><Button type="submit" size="lg">Solicitar visita de ejemplo <ArrowUpRight /></Button></form>}</div></div></section>;
}
